### ISSUE TITLE
Creative Tab not localized

### ISSUE THREAD

**Issue by Remyrios** [xt9/DeepMobLearning-BloodMagic#1]
DeepMobLearning BloodMagic Addon version - 0.9.0
DeepMobLearning version - 2.0.4
Forge version - 14.23.4.2750

Description:
As title says

**Comment by xt9** [comment]
Aye aye, will fix.

**Comment by xt9** [comment]
Fixed in  3634c7c385ee2b901253e91247fd1f30cbef0f33
