### ISSUE TITLE
Data Model Disappear from Agonizer

### ISSUE THREAD

**Issue by desagas** [xt9/DeepMobLearning-BloodMagic#4]
Version deepmoblearningbm-1.12.2-1.0.1-universal.

On vanilla FTB Interactions 1.9.1

In the past two 24 hours of game play time, two of my self-aware models have disappeared from the agonizer. I am not sure what has caused it, but I will try and watch more closely. I believe it may have something to do with a full blood altar on reloading the world, but I am not positive. I will update when I have more information.

**Comment by desagas** [comment]
Correction. This is not your issue. I had my agonizer beside a gregtech input bus, and it automatically extracts from adjacent inventories.

**Comment by xt9** [comment]
Thanks for following up!
