### ISSUE TITLE
Runes of Sacrifice not being detected

### ISSUE THREAD

**Issue by jay11800** [xt9/DeepMobLearning-BloodMagic#6]
Playing on a FTB: Interactions server, and I can't seem to get the deeb mob agonizer to detect the Runes of sacrifice that are in my altar. I confirmed its a valid tier 3 altar, am I doing something wrong, or is this a bug?

![image](https://user-images.githubusercontent.com/5142933/111237642-e57d9500-85cb-11eb-8958-c1e9131e7e81.png)

![image](https://user-images.githubusercontent.com/5142933/111237661-f0d0c080-85cb-11eb-9e19-69765ce64304.png)

**Comment by Onii-133** [comment]
Just in case it comes up, the arrow just says I was missing a model, put one in and it didn't update the runes detected

**Comment by Onii-133** [comment]
FTB Interacts has custom caps, and the Animus Altar Diviner told me the incorrect block data, so it was never a finished altar. 
Apologies
